# Generated by Django 6.0.3 on 2026-05-26 19:06

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('categoria', models.CharField(choices=[('suplemento', 'Suplemento'), ('equipamiento', 'Equipamiento'), ('accesorio', 'Accesorio'), ('ropa', 'Ropa Deportiva')], max_length=15)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='productos/')),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('altura', models.FloatField(blank=True, help_text='Altura en cm', null=True)),
                ('peso', models.FloatField(blank=True, help_text='Peso en kg', null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Medicion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('peso', models.FloatField(blank=True, null=True)),
                ('altura', models.FloatField(blank=True, null=True)),
                ('imc', models.FloatField(blank=True, help_text='Índice de Masa Corporal', null=True)),
                ('grasa_corporal', models.FloatField(blank=True, help_text='Porcentaje', null=True)),
                ('masa_muscular', models.FloatField(blank=True, help_text='kg', null=True)),
                ('pecho', models.FloatField(blank=True, help_text='cm', null=True)),
                ('cintura', models.FloatField(blank=True, null=True)),
                ('cadera', models.FloatField(blank=True, null=True)),
                ('biceps', models.FloatField(blank=True, null=True)),
                ('notas', models.TextField(blank=True, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mediciones', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Objetivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('peso_objetivo', models.FloatField(blank=True, null=True)),
                ('fecha_inicio', models.DateField()),
                ('fecha_objetivo', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(default='activo', max_length=20)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objetivos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('pagado', 'Pagado'), ('procesando', 'Procesando'), ('enviado', 'Enviado'), ('entregado', 'Entregado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=15)),
                ('notas', models.TextField(blank=True, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metodo', models.CharField(choices=[('tarjeta', 'Tarjeta de Crédito/Débito'), ('transferencia', 'Transferencia Bancaria'), ('mercadopago', 'MercadoPago'), ('paypal', 'PayPal')], max_length=20)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado'), ('reembolsado', 'Reembolsado')], default='pendiente', max_length=15)),
                ('fecha_pago', models.DateTimeField(blank=True, null=True)),
                ('referencia_externa', models.CharField(blank=True, max_length=100, null=True)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='core.pedido')),
            ],
        ),
        migrations.CreateModel(
            name='PlanEntrenamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('tipo', models.CharField(choices=[('fuerza', 'Entrenamiento de Fuerza'), ('cardio', 'Cardio'), ('hiit', 'HIIT'), ('flexibilidad', 'Flexibilidad'), ('mixto', 'Entrenamiento Mixto')], max_length=15)),
                ('duracion_semanas', models.PositiveIntegerField()),
                ('frecuencia_semanal', models.PositiveIntegerField(help_text='Días por semana')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planes_entrenamiento', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ejercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('serie', models.PositiveIntegerField(help_text='Número de series')),
                ('repeticiones', models.CharField(help_text='Repeticiones por serie', max_length=50)),
                ('descanso_segundos', models.PositiveIntegerField(default=60)),
                ('musculo', models.CharField(choices=[('pecho', 'Pecho'), ('espalda', 'Espalda'), ('piernas', 'Piernas'), ('hombros', 'Hombros'), ('brazos', 'Brazos'), ('abdomen', 'Abdomen'), ('completo', 'Cuerpo Completo')], max_length=15)),
                ('explicacion', models.TextField(blank=True, null=True)),
                ('plan_entrenamiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ejercicios', to='core.planentrenamiento')),
            ],
        ),
        migrations.CreateModel(
            name='PlanNutricional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('objetivo_calorico', models.PositiveIntegerField(help_text='Calorías diarias objetivo')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planes_nutricionales', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('desayuno', 'Desayuno'), ('almuerzo', 'Almuerzo'), ('merienda', 'Merienda'), ('cena', 'Cena'), ('snack', 'Snack')], max_length=15)),
                ('nombre', models.CharField(max_length=200)),
                ('hora', models.TimeField(blank=True, null=True)),
                ('kcal', models.PositiveIntegerField()),
                ('proteinas', models.FloatField(blank=True, help_text='gramos', null=True)),
                ('carbohidratos', models.FloatField(blank=True, help_text='gramos', null=True)),
                ('grasas', models.FloatField(blank=True, help_text='gramos', null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('plan_nutricional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comidas', to='core.plannutricional')),
            ],
        ),
        migrations.CreateModel(
            name='PedidoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.pedido')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.producto')),
            ],
        ),
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.producto')),
            ],
        ),
        migrations.CreateModel(
            name='Profesional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especialidad', models.CharField(choices=[('entrenador', 'Entrenador Personal'), ('nutricionista', 'Nutricionista'), ('fisioterapeuta', 'Fisioterapeuta'), ('medico', 'Médico Deportivo')], max_length=20)),
                ('numero_licencia', models.CharField(blank=True, max_length=50, null=True)),
                ('biografia', models.TextField(blank=True, null=True)),
                ('precio_consulta', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='plannutricional',
            name='profesional',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.profesional'),
        ),
        migrations.AddField(
            model_name='planentrenamiento',
            name='profesional',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.profesional'),
        ),
        migrations.CreateModel(
            name='ProgresoEntrenamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('peso_usado', models.FloatField(blank=True, null=True)),
                ('reps_completadas', models.PositiveIntegerField()),
                ('completado', models.BooleanField(default=False)),
                ('ejercicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ejercicio')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Suscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('basico', 'Básico'), ('premium', 'Premium'), ('pro', 'Pro')], max_length=15)),
                ('precio_mensual', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_inicio', models.DateField()),
                ('fecha_renovacion', models.DateField()),
                ('estado', models.CharField(choices=[('activa', 'Activa'), ('vencida', 'Vencida'), ('cancelada', 'Cancelada')], default='activa', max_length=15)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suscripciones', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
