# Generated by Django 6.0.3 on 2026-08-11 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('admin', 'Admin'), ('cliente', 'Cliente'), ('vendedor', 'Vendedor')], default='cliente', max_length=15),
        ),
    ]
